### ISSUE TITLE
BI box

### ISSUE THREAD

**Issue by martent** [malmostad/intranet-dashboard#47]
@jesperbylund wrote in email:

Skulle vi kunna samla lite mer och bygga en BI-box med dessa data? BI-boxen ska visas för dem som valt kommunikationsarbete som arbetsfält.
## Idéer
1. Balans desktop-/mobil-användning denna vecka
2. Antal inloggade hittills denna vecka
3. Antal laddningar av dashboarden denna vecka
4. Aktiva senaste timmen
5. Plotta mobilanvändandet på karta, var accesser medarbetare Komin med mobilen?
6. 3 bästa förvaltningarna (användningsfrekvens denna vecka)
7. Antal sökningar i kontaktboken denna vecka

**Comment by magnivar** [comment]
Closed in favor of #52
