### ISSUE TITLE
Enhancements front-end in the box "Verktyg & system" and "Jag vill"

### ISSUE THREAD

**Issue by jesperbylund** [malmostad/intranet-dashboard#50]
Scope: Make it more obvious that it is possible to adjust the content in the dashboard box "Verktyg & system". Expand the possibilities to personalize the box.

* Make it possible to un-choose all verktyg/system in the personal list (https://webapps06.malmo.se/dashboard/users/select_shortcuts/tools_and_systems) (today some is not possible to un-choose)
* Throw away-x to the right side of every link (as in the box Mina arbetskamrater)
* Lik for adding a verktyg/system in the bottom of the box (as in the box Mina arbetskamrater). Link goes to https://webapps06.malmo.se/dashboard/users/select_shortcuts/tools_and_systems

![enh_verktygsystem](https://cloud.githubusercontent.com/assets/3509721/3747080/cb25ea1c-17c9-11e4-85e4-aeed667747fa.png)

**Comment by martent** [comment]
Replaced by #61.
