### ISSUE TITLE
Enhance the user's feed stream

### ISSUE THREAD

**Issue by martent** [malmostad/intranet-dashboard#60]
Enhance the user's feed stream so that it is:

* Always combined into one stream
* Has labels for the category it belongs to taken from the feeds label.
* Unbox the boxed look-and-feel for the stream.
* Larger images for the first 3 news items
* Placeholder image for news items with missing thumbnails.

**Comment by martent** [comment]
Deployed in test @olajoh1. Review before I deploy in production.

**Comment by olajoh1** [comment]
Hur kan jag testa prioordningen för etiketteringen?

**Comment by martent** [comment]
Du menar vilken av flera kategorier som egentligen visas? Det beror på flera faktorer som är svåra att testa. En användare kan ha en nyhet i sitt flöde från ett antal flöden. Tittar man på den här:

https://webapps04.malmo.se/nyheter/2015/04/29/kommunmasterskap-i-golf-2015/

och betänker att en användare har minst två roller som man i admin för flödena kan ha associerat med ett antal av dessa flöden och lägger till att användaren själv kan ha valt till befintliga flöden och lagt till egna flöden så finns det tusentals möjligheter. 

Frågan är vad vi ska testa när vi idag inte har byggt någon aktiv sortering av kategorier i WP (bokstavsordning per default) och inte har satt någon prioritering av olika flöden eller roller i Min sida. Vi måste rita upp och bygga en prioriteringslogik innan vi kan testa något. Detta är inget som ändrats sen föregående versioner av Min sida.

**Comment by olajoh1** [comment]
Precis jag vill testa logiken för vilken kategori som visas, t.ex. om en nyhet har kategorierna Vår kommun och Kommunikationsarbete, vilken visas i flödet?



Från: Mårten Thavenius [mailto:notifications@github.com]
Skickat: den 6 maj 2015 09:43
Till: malmostad/intranet-dashboard
Kopia: Ola Johansson
Ämne: Re: [intranet-dashboard] Enhance the user's feed stream (#60)


Du menar vilken av flera kategorier som egentligen visas? Det beror på flera faktorer som är svåra att testa. En användare kan ha en nyhet i sitt flöde från ett antal flöden. Tittar man på den här:

https://webapps04.malmo.se/nyheter/2015/04/29/kommunmasterskap-i-golf-2015/

och betänker att en användare har minst två roller som man i admin för flödena kan ha associerat med ett antal av dessa flöden och lägger till att användaren själv kan ha valt till befintliga flöden och lagt till egna flöden så finns det tusentals möjligheter.

Frågan är vad vi ska testa när vi idag inte har byggt någon aktiv sortering av kategorier i WP (bokstavsordning per default) och inte har satt någon prioritering av olika flöden eller roller i Min sida. Vi måste rita upp och bygga en prioriteringslogik innan vi kan testa något. Detta är inget som ändrats sen föregående versioner av Min sida.

**Comment by martent** [comment]
Då får vi först speca och bygga logiken. Se ovan.

**Comment by olajoh1** [comment]
Vad styr idag då? Den kategori som kommer först?

**Comment by martent** [comment]
Den enda logik som aktivt har byggts är att det i visningsläget ses till att en nyhet inte visas två eller fler gånger. Det har aldrig funnits i någon kravbild att bygga en intelligent logik för administration och urval av **vilken** av exakt **samma** nyhet som visas för en användare när den finns i mängder av olika flöden som admin eller användaren lagt upp. Etiketterna som visas är inget nytt, de har bara en annan design.

Jag kan beskriva vad som i praktiken händer, och kan hända beroende på olika källsystem för nyheterna, men det krävs ett eget BC för det.

**Comment by olajoh1** [comment]
Det är inget nytt men jag får säkert frågan ändå. Vad du alltså säger är att det inte i en mening låter sig beskrivas vad som gör att en nyhet, som har flera kategorier, visas med en viss kategori i flödet?

**Comment by martent** [comment]
Om det går att förutsäga eller om det är slumpmässigt beror på om man är determinist eller inte vilket kan variera från person till person.

Varje nyhet finns oftast i ett antal flöden som ni lagt upp för Min sida och de hämtas och uppdateras löpande med en cykel som tar c:a tre minuter (idag, men det beror på serverkraft, nätverksstatus och antal flöden). När en ny nyhet publiceras så får Min sida in den via ett eller fler flöden. Om motorn som hämtar hem nyheter, det finns c:a 75000 i systemet, precis då hämtar hem flöde nummer 315 och den finns där så är det det flödes namn som kommer att visas i de användaren som har flöde 315 genom en roll eller sina egna val. När motorn kommer vidare till flöde 402 efter någon minut kanske nyheten finns i det flödet också. De användare som genom någon association har flöde 315 och 402 får fortfarande namnet på flöde 315 som etikett. En annan användare som inte har en relation till flöde 315 men däremot till 402 får namnet på det flödet som etikett (i flödesnamnet tar vi på ditt önskemål bort "Nyheter", "Blogg" samt namnet på forumet).

Så för att testa det får du följa motorn som hanterar 75000 nyheter (äldre än två veckor tas bort) och se om en person som har en relation till ett visst flöde som motorn i sin cykel precis är på väg att hämta också får det flödets namn som etikett (rätt) eller om den får ett senare flödes namn (ett flöde hen också har relation till) (bugg, men det spelar ingen roll eftersom det är "slumpmässigt" var i sin cykel motorn befinner sig när någon klickar på "Publicera").

**Comment by olajoh1** [comment]
Mao slumpmässigt. 

Då tycker jag vi är nöjda. Återstår bara att synka deploy med nyhet som Nina lägger ut. 

När passar det dig att deploya?

**Comment by martent** [comment]
Närsom. Det brukar bli zero-downtime deployment.

**Comment by olajoh1** [comment]
ok, då bestämmer jag något med Nina.

**Comment by martent** [comment]
I produktion innan semestern.
