### ISSUE TITLE
Detach links in "Verktyg & system" and "Jag vill" from roles

### ISSUE THREAD

**Issue by martent** [malmostad/intranet-dashboard#61]
Draft to a specification based on @olajoh1's input. This issue replaces #50 and #51.

Links in the boxes "Verktyg & system" and "Jag vill" are today role based in the same way as the news feed on the dashboard. User profiles are associated with roles, roles are associated with links and news feeds. The associations are managed by administrators.

The new idea is to detach the links from the roles and attach them directly to the user profiles. The user will be able to remove every link from her profile by clicking on a remove "x" next to the link. To add a link, she will have to go to the full list of links for either Verktyg och Jag vill (146 in total right now) and select one or more.

An administrator will still add, change and remove links. Removed links will be removed from user profiles. Questions:

1. Should the "role" property still be [associated with a link](https://webapps06.malmo.se/dashboard/shortcuts/67/edit). If yes:
1. What happens if an administrator add a new link? Should it be attached to all user profiles that are associated with the role(s) the administrator selects?
1. What happens if an administrator change the roles for an existing link? Should it be detached from user profiles associated with a role that is deselected? And should this happen even if the user selected the link herself? 
1. If the administrator add a role to a link, should it be attached to all user profiles associated with that role?
1. If a user selects a role, what will happen to the links associated with that role in her user profile?
1. If a user deselects a role, what will happen to the links associated with that role in her user profile?
1. Should it be possible to entirely reset all links to the current roles of a user profile?
1. When a user logs on to the dashboard for the first time a user profile is created. The user can then select one or more roles. This is the same process as she is using when adding more roles later on (see above).

**Comment by martent** [comment]
Meeting with @olajoh1. Answers:
 
> Should the "role" property still be associated with a link. If yes:

Yes

>What happens if an administrator add a new link? Should it be attached to all user profiles that are 
associated with the role(s) the administrator selects?

Nothing should happen. This will only affect new users.

> What happens if an administrator change the roles for an existing link? Should it be detached from user profiles associated with a role that is deselected? And should this happen even if the user selected the link herself?

Nothing should happen. This will only affect new users.

> If the administrator add a role to a link, should it be attached to all user profiles associated with that role?

Nothing should happen. This will only affect new users.

> If a user selects a role, what will happen to the links associated with that role in her user profile?

Nothing.

> If a user deselects a role, what will happen to the links associated with that role in her user profile?

Nothing.

> Should it be possible to entirely reset all links to the current roles of a user profile?

Reset to default is a nice to have. 

> When a user logs on to the dashboard for the first time a user profile is created. The user can then select one or more roles. This is the same process as she is using when adding more roles later on (see above).

Differentiate between the first selection of a department and working field and later changes. The first selection will add the collection of inks from that role(s). Secondary changes to roles will not add any links.

**Comment by martent** [comment]
All features above developed and deployed in test. The "reset" feature is per categories, i.e. "Jag vill" and "Mina verktyg och system".

I have deleted your user in the test environment @olajoh1 so you can test the logic above in the full workflow. It is easy to remove the user again.

Question: All users shortcuts are migrated in test so that they are attached directly to the users. It is a ~15 minute job to run and during that time the users will not have any shortcuts, they will get them back user by user in the order they signed up. Should we use the maintenance page during that time in prod so employees are not confused?

**Comment by olajoh1** [comment]
Is´t possible to run the job during off peak hours?

**Comment by olajoh1** [comment]
Could you delete my user again?

**Comment by martent** [comment]
Done.

**Comment by olajoh1** [comment]
When
1) deleting pre-populated links and then
2) adding new links
the result shows deleted pre-populated links again

**Comment by martent** [comment]
Confirmed. A bug introduced with the statistics logging. Will take some time to fix so there will not be any deployment in prod today.

**Comment by martent** [comment]
I had to change some of the logic for role assignments of shortcuts to get rid of the bug the last minute change introduced. So testing must start over from the beginning. I have deleted your user again.

**Comment by olajoh1** [comment]
Buggen kan inte återskapas nu

**Comment by martent** [comment]
Deploy gjord i produktion.
