### ISSUE TITLE
Track profile changes for shortcuts

### ISSUE THREAD

**Issue by martent** [malmostad/intranet-dashboard#62]
Add boolean column and set the value to true when an employee make her first change to her shortcuts.

Add a count for this value to the report page in admin.

@olajoh1

**Comment by martent** [comment]
This feature is deployed in test.

The statistics page in the admin section shows the number of users who have removed and/or added shortcuts manually to their profile. Not that the statistics page is cached for 6 hours since it is a heavy report to run.

The bug with unique values on the statistics page is also fixed.

Your user is set to admin so you can check the statistics.

This will be a part of the #61 release.

**Comment by olajoh1** [comment]
Kan inte se att jag har admin-behörighet

**Comment by martent** [comment]
När jag tar bort din användare så skapas en helt ny profil när du loggar in nästa gång, på samma sätt som för en nyanställd. Den användaren blir inte administratör automatiskt. Jag har gett den nya användarprofilen admin-behörighet nu.

**Comment by olajoh1** [comment]
ok, när passar det att vi deployar?

**Comment by martent** [comment]
Antingen idag på lunchen så att du hinner kolla av och jag kan fixa om det behövs i eftermiddag. Eller sent på torsdag eftermiddag så kan jag ta mindre fixar på fredagen.

**Comment by olajoh1** [comment]
Var det inte denna deploy som kunde störa och som vi därför sa att den skulle göras någon kväll?

**Comment by martent** [comment]
Det kommer att vara en kontrollerad nedtid där denna sidan visas under c:a 15 minuter:
http://webapps06.malmo.se/maintenance.html

Jag har inte tid någon kväll denna veckan men kan planera in det efter kontorstid någon dag i nästa vecka. Lämpligtvis inte tisdagen eftersom jag inte är på Malmö stad på onsdagar.

**Comment by olajoh1** [comment]
Jag tycker vi väntar tills du har tid någon dag utanför fönstret 07:30-17:30. Föreslå en dag då det passar dig.

**Comment by martent** [comment]
Måndag 19/10.

**Comment by martent** [comment]
@olajoh1, Petra och supporten vill ha info från dig om att vi kommer att ha nedtid, jag har berättat för henne mer informellt när jag träffade henne.

**Comment by olajoh1** [comment]
Vilken tid tar du ner Komin?

**Comment by martent** [comment]
Mellan 21.00 och 22.00. Faktisk nedtid beräknas till 15 minuter.

**Comment by martent** [comment]
Utfört. Stänger här och lämnar över till @olajoh1 stänger huvudbiljetten #61.
