### ISSUE TITLE
Links in edit mode in the staff directory wrong, change to new target page

### ISSUE THREAD

**Issue by jesperbylund** [malmostad/intranet-dashboard#66]
Links to "IT-kompassen" leads to error page. Update with new link. (Page is edit mode for profile page in the staff directory.)
![telefonandring](https://cloud.githubusercontent.com/assets/3509721/15501226/ac3346ba-21ac-11e6-86b7-c80d95b49889.jpg)

**Comment by martent** [comment]
@jesperbylund Do you have the correct link?

**Comment by martent** [comment]
cc @susjon11

**Comment by susjon11** [comment]
New link:  
http://marval.malmo.se/msmselfservice/ServiceCatalogueEx.aspx?g=13

**Comment by pbrotherton** [comment]
Deployed in production
