### ISSUE TITLE
New link/button

### ISSUE THREAD

**Issue by martent** [malmostad/intranet-dashboard#68]
@pbrotherton:  Place a new direct link/button on the dashboard where the migration link were before. Same markup (check the history in the source code).

Make a deploy in the test env. We need to check if the text will fit in on all device widths or if we need to change the wording or styling or insert a soft hyphen in the long word.

Name: Allt om organisationsöversynen
Link: https://komin.malmo.se/Var-kommun/Organisationsoversyn-2016.html

cc: @susjon11 @jesperbylund

**Comment by pbrotherton** [comment]
Hi Mårten,

Hope all is well - is this something I need to deal with immediately or
should it wait until I am back at Malmö Stad again, do you know?

Kind regards,

Paul Brotherton
Developer
paul.brotherton@whitespace.se
070-896 49 99

Whitespace - Fersens väg 3, 211 42 Malmö - http://www.whitespace.se

2016-09-05 14:25 GMT+02:00 Mårten Thavenius <notifications@github.com>:

**Comment by martent** [comment]
As soon as you can.

**Comment by pbrotherton** [comment]
All done (on staging). Will wait to push to git...

**Comment by martent** [comment]
I can se that the last world is too long on some device widths when I adjust the browser width. Can you place a soft hyphen in it so it will be hyphened when there isn't enough room:

    Allt om organisations­&shy;översynen

**Comment by susjon11** [comment]
Om det blir trångt med bokstäver önskar Lisa att det står såhär, detta är 1:a, 2:a och 3:e val.


1.       Allt om organisationsöversynen

2.       Om organisationsöversynen

3.       Organisationsöversynen

/Susanne

Från: Mårten Thavenius [mailto:notifications@github.com]
Skickat: den 8 september 2016 09:35
Till: malmostad/intranet-dashboard
Kopia: Susanne Jönsson; Mention
Ämne: Re: [malmostad/intranet-dashboard] New link/button (#68)


I can se that the last world is too long on some device widths when I adjust the browser width. Can you place a soft hyphen in it so it will be hyphened when there isn't enough room:

Allt om organisations­&shy;översynen

**Comment by pbrotherton** [comment]
Fixed (staging, not pushed)

**Comment by martent** [comment]
Alright, chose alternative (3) in Susannes reply, and keep it shy :)

Deploy in staging and production, push to GH and create a git release tag.

**Comment by pbrotherton** [comment]
Deployed to staging & production, tagged and pushed.

**Comment by martent** [comment]
Excellent.
