### ISSUE TITLE
Bugg i mina arbetskamrater

### ISSUE THREAD

**Issue by olajoh1** [malmostad/intranet-dashboard#71]
Datum och tidsstämpel saknas för de nyanställda.

![image](https://cloud.githubusercontent.com/assets/6176181/19918890/3ddd01f4-a0cf-11e6-9167-2856c6596fb9.png)

@martent

**Comment by martent** [comment]
Uppdaterar man sin status från Min sida, högst upp i rutan, får man alltid en tidsstämpel men inte om man gör det via sidan där man redigerar sin profil. Det har varit en known-issue sen första versionen av Min sida, men bedömdes inte vara rationellt att fixa eftersom de som håller statusen uppdaterad gör det från Min sida och får en tidsstämpel. En uppdatering man endast gör en gång, när man är nyanställd och går till sin profilsida räknades inte som tids-relevant. Men det kan ju finnas de som går in i sin profil och ändrar där regelbundet, även om det är omständligt.

Detta är ju dock inget argument för att det inte kan ändras.

**Comment by magnivar** [comment]
Kolla om det skall göras nåt åt.

**Comment by magnivar** [comment]
Gör inget med detta
