### ISSUE TITLE
Fel på typsnitt och sökruta

### ISSUE THREAD

**Issue by susjon11** [malmostad/intranet-dashboard#72]
Vi har pratat om detta förut och jag skulle meddela när det hände igen...

Min sida ser bra ut.. klickar sen på en nyhet och då ser det ut enligt skärmdump
![fel_pa_typsnitt_och_sokruta_001](https://cloud.githubusercontent.com/assets/3829956/20752401/883433ba-b701-11e6-89e0-f303ed49392f.png)

**Comment by martent** [comment]
Ser ut som om din Internet Explorer slagit över till att använda motorn från IE7 (en feature i IE). Låt Magnus kolla om det är så, jag har visat honom hur man gör det.

Det har varit problem med att det skjuts ut fel inställningar till plattformdatorerna under flera år som gör att detta inträffar på vissa webbtjänster på domänen *.malmo.se där det inte ska ske.

**Comment by susjon11** [comment]
Grundläget är Edge-Standard och när jag klickar på en nyhet så skiftar den själv.
Se screencapture-film här: http://www.screencast.com/t/kKnGu8kcCv

**Comment by susjon11** [comment]
Bytte till Edge på nyheten och IE verkar komma ihåg det.
Så... jag stänger detta.

**Comment by martent** [comment]
Det bäst dokumenterade felet i år!

**Comment by magnivar** [comment]
Ja, vi inför en ny standard tycker jag.. är det inte lika bra dokumenterat som detta så åtgärdas det inte :)
